INSERT INTO GROUPS(GROUP_ID,GROUP_NAME,GROUP_STATUS) VALUES(1,'Daily','Active');
INSERT INTO GROUPS(GROUP_ID,GROUP_NAME,GROUP_STATUS) VALUES(2,'Education','Active');
INSERT INTO GROUPS(GROUP_ID,GROUP_NAME,GROUP_STATUS) VALUES(3,'Sports','Nonactive');
INSERT INTO TASK(TASK_ID,TASK_END_DATE,TASK_NAME,TASK_PRIORITY,TASK_START_DATE,TASK_STATUS,GROUP_ID) VALUES(1,'20-04-03','Grocery','Important','20-04-03','Active',1);
INSERT INTO TASK(TASK_ID,TASK_END_DATE,TASK_NAME,TASK_PRIORITY,TASK_START_DATE,TASK_STATUS,GROUP_ID) VALUES(2,'20-04-03','Milk','Important','20-04-03','Active',1);
INSERT INTO TASK(TASK_ID,TASK_END_DATE,TASK_NAME,TASK_PRIORITY,TASK_START_DATE,TASK_STATUS,GROUP_ID) VALUES(3,'20-04-02','Science','Important','20-01-01','Active',2);
INSERT INTO TASK(TASK_ID,TASK_END_DATE,TASK_NAME,TASK_PRIORITY,TASK_START_DATE,TASK_STATUS,GROUP_ID) VALUES(4,'20-04-02','Maths','Important','20-01-01','Active',2);